# ============================================================
# Copy Patch to WoW Data Directory
# Copies patch-Z.MPQ from patches/ to WoW/Data/ for web server
# ============================================================

param(
    [string]$XamppPath = "C:\xampp",
    [string]$SourcePatch = "$XamppPath\htdocs\patches\patch-Z.MPQ",
    [string]$DestPath = "$XamppPath\htdocs\WoW\Data\patch-Z.MPQ"
)

Write-Host "=== Copying Patch to WoW Data Directory ===" -ForegroundColor Cyan

# Check if source patch exists
if (-not (Test-Path $SourcePatch)) {
    Write-Host "✗ Source patch not found: $SourcePatch" -ForegroundColor Red
    Write-Host "`nThe patch file should be generated by the server on startup." -ForegroundColor Yellow
    Write-Host "Make sure:" -ForegroundColor Yellow
    Write-Host "  1. Server has started and generated the patch" -ForegroundColor White
    Write-Host "  2. ProgressiveSystems.DBC.WebServerPath is set in config" -ForegroundColor White
    Write-Host "  3. ProgressiveSystems.DBC.AutoGenerateMPQ = true" -ForegroundColor White
    Write-Host "  4. pympq is installed (pip install pympq)" -ForegroundColor White
    exit 1
}

Write-Host "✓ Source patch found: $SourcePatch" -ForegroundColor Green

# Create destination directory if needed
$destDir = Split-Path -Parent $DestPath
if (-not (Test-Path $destDir)) {
    New-Item -ItemType Directory -Path $destDir -Force | Out-Null
    Write-Host "✓ Created directory: $destDir" -ForegroundColor Green
} else {
    Write-Host "✓ Destination directory exists: $destDir" -ForegroundColor Green
}

# Copy the patch file
try {
    Copy-Item -Path $SourcePatch -Destination $DestPath -Force
    Write-Host "✓ Patch copied successfully!" -ForegroundColor Green
    Write-Host "  From: $SourcePatch" -ForegroundColor White
    Write-Host "  To:   $DestPath" -ForegroundColor White
    
    # Show file info
    $fileInfo = Get-Item $DestPath
    Write-Host "`nFile Info:" -ForegroundColor Cyan
    Write-Host "  Size: $([math]::Round($fileInfo.Length / 1MB, 2)) MB" -ForegroundColor White
    Write-Host "  Modified: $($fileInfo.LastWriteTime)" -ForegroundColor White
    
    Write-Host "`n✓ Patch is now available at:" -ForegroundColor Green
    Write-Host "  http://localhost/WoW/Data/patch-Z.MPQ" -ForegroundColor White
    Write-Host "  (or http://myclubgames.com/WoW/Data/patch-Z.MPQ)" -ForegroundColor White
    
} catch {
    Write-Host "✗ Failed to copy patch: $_" -ForegroundColor Red
    exit 1
}

Write-Host "`n=== Done ===" -ForegroundColor Green

