# ============================================================
# Setup Web Server for WoW Launcher
# Configures XAMPP to serve game files and patches
# ============================================================

Write-Host "=== WoW Launcher Web Server Setup ===" -ForegroundColor Cyan

# XAMPP paths
$xamppPath = "C:\xampp"
$htdocsPath = "$xamppPath\htdocs"
$patchesPath = "$htdocsPath\patches"

# Check if XAMPP exists
if (-not (Test-Path $xamppPath)) {
    Write-Host "✗ XAMPP not found at: $xamppPath" -ForegroundColor Red
    Write-Host "Please install XAMPP or update the path in this script." -ForegroundColor Yellow
    exit 1
}

Write-Host "✓ XAMPP found at: $xamppPath" -ForegroundColor Green

# Create patches directory
if (-not (Test-Path $patchesPath)) {
    New-Item -ItemType Directory -Path $patchesPath -Force | Out-Null
    Write-Host "✓ Created patches directory: $patchesPath" -ForegroundColor Green
} else {
    Write-Host "✓ Patches directory exists: $patchesPath" -ForegroundColor Green
}

# Check for game ZIP
$gameZip = "$htdocsPath\WOTLKHD.zip"
if (Test-Path $gameZip) {
    Write-Host "✓ Game ZIP found: $gameZip" -ForegroundColor Green
} else {
    Write-Host "⚠ Game ZIP not found: $gameZip" -ForegroundColor Yellow
    Write-Host "  Place WOTLKHD.zip in: $htdocsPath" -ForegroundColor Yellow
}

# Create version.txt file (placeholder)
$versionFile = "$patchesPath\version.txt"
if (-not (Test-Path $versionFile)) {
    $timestamp = [int](Get-Date -UFormat %s)
    Set-Content -Path $versionFile -Value $timestamp
    Write-Host "✓ Created version file: $versionFile" -ForegroundColor Green
}

# Check for patch-Z.MPQ
$patchFile = "$patchesPath\patch-Z.MPQ"
if (Test-Path $patchFile) {
    Write-Host "✓ Patch file found: $patchFile" -ForegroundColor Green
} else {
    Write-Host "⚠ Patch file not found: $patchFile" -ForegroundColor Yellow
    Write-Host "  Patch will be generated by server on startup" -ForegroundColor Yellow
}

# Create .htaccess for proper MIME types
$htaccessPath = "$patchesPath\.htaccess"
$htaccessContent = @"
# Allow MPQ files
AddType application/octet-stream .MPQ
AddType application/octet-stream .mpq

# Enable directory listing (optional)
Options +Indexes
"@

Set-Content -Path $htaccessPath -Value $htaccessContent
Write-Host "✓ Created .htaccess for MPQ files" -ForegroundColor Green

# Create latest directory for symlink
$latestPath = "$patchesPath\latest"
if (-not (Test-Path $latestPath)) {
    New-Item -ItemType Directory -Path $latestPath -Force | Out-Null
    Write-Host "✓ Created latest directory: $latestPath" -ForegroundColor Green
}

# Create symlink for latest patch (if patch exists)
if (Test-Path $patchFile) {
    $latestPatch = "$latestPath\patch-Z.MPQ"
    if (-not (Test-Path $latestPatch)) {
        # Create junction/symlink
        cmd /c mklink "$latestPatch" "$patchFile" 2>&1 | Out-Null
        if (Test-Path $latestPatch) {
            Write-Host "✓ Created symlink: $latestPatch -> $patchFile" -ForegroundColor Green
        }
    }
}

Write-Host "`n=== Setup Complete ===" -ForegroundColor Green
Write-Host "`nWeb Server URLs:" -ForegroundColor Cyan
Write-Host "  Game ZIP: http://localhost/WOTLKHD.zip" -ForegroundColor White
Write-Host "  Patch Version: http://localhost/patches/version.txt" -ForegroundColor White
Write-Host "  Patch Download: http://localhost/patches/latest/patch-Z.MPQ" -ForegroundColor White
Write-Host "`nNext Steps:" -ForegroundColor Cyan
Write-Host "  1. Start XAMPP Apache server" -ForegroundColor White
Write-Host "  2. Place WOTLKHD.zip in: $htdocsPath" -ForegroundColor White
Write-Host "  3. Run launcher: python tools/wow_launcher.py" -ForegroundColor White
Write-Host "`nNote: Update server_url in launcher_config.json if not using localhost" -ForegroundColor Yellow

